 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/order_lines", type: :request do
  
  # OrderLine. As you add validations to OrderLine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrderLine.create! valid_attributes
      get order_lines_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order_line = OrderLine.create! valid_attributes
      get order_line_url(order_line)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_order_line_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      order_line = OrderLine.create! valid_attributes
      get edit_order_line_url(order_line)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrderLine" do
        expect {
          post order_lines_url, params: { order_line: valid_attributes }
        }.to change(OrderLine, :count).by(1)
      end

      it "redirects to the created order_line" do
        post order_lines_url, params: { order_line: valid_attributes }
        expect(response).to redirect_to(order_line_url(OrderLine.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrderLine" do
        expect {
          post order_lines_url, params: { order_line: invalid_attributes }
        }.to change(OrderLine, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post order_lines_url, params: { order_line: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested order_line" do
        order_line = OrderLine.create! valid_attributes
        patch order_line_url(order_line), params: { order_line: new_attributes }
        order_line.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the order_line" do
        order_line = OrderLine.create! valid_attributes
        patch order_line_url(order_line), params: { order_line: new_attributes }
        order_line.reload
        expect(response).to redirect_to(order_line_url(order_line))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        order_line = OrderLine.create! valid_attributes
        patch order_line_url(order_line), params: { order_line: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested order_line" do
      order_line = OrderLine.create! valid_attributes
      expect {
        delete order_line_url(order_line)
      }.to change(OrderLine, :count).by(-1)
    end

    it "redirects to the order_lines list" do
      order_line = OrderLine.create! valid_attributes
      delete order_line_url(order_line)
      expect(response).to redirect_to(order_lines_url)
    end
  end
end
